services:
  nginx-proxy:
    container_name: nginx-proxy
    build: .
    restart: always
    ports:
      - "80:80"
      - "443:443"
    logging:
      options:
        max-size: "50m"
        max-file: "10"
    volumes:
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro

  acme-companion:
    image: nginxproxy/acme-companion:latest
    container_name: acme-companion
    restart: always
    env_file:
      - .env
    logging:
      options:
        max-size: "50m"
        max-file: "10"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - acme:/etc/acme.sh
    depends_on:
      - nginx-proxy

volumes:
  certs:
  html:
  vhost:
  acme:

networks:
  default:
    name: shared-web
    external: true
